# Configurações da Fonte de Dados (DataSource)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=teste
spring.datasource.password=teste

# Ativa o Console do H2 no navegador
spring.h2.console.enabled=true
# Define o caminho para acessar o console (ex: localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true